import express from "express";
import cors from "cors";
import { PORT, NODE_ENV } from "./config/env";
import authRoutes from "./routes/auth";
import userRoutes from "./routes/users";
import productRoutes from "./routes/products";
import cartRoutes from "./routes/cart";
import orderRoutes from "./routes/orders";
import walletRoutes from "./routes/wallet";
import paymentRoutes from "./routes/payment";
import healthRoutes from "./routes/health";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/products", productRoutes);
app.use("/api/cart", cartRoutes);
app.use("/api/orders", orderRoutes);
app.use("/api/wallet", walletRoutes);
app.use("/api/payment", paymentRoutes);
app.use("/api", healthRoutes);
app.listen(PORT, () => {});